import { randomBytes, scryptSync, timingSafeEqual } from "node:crypto";

/**
 * The read-only git remote password. Generated by Amber, shown to the user
 * exactly once, and stored only as a scrypt hash. Plaintext never touches the
 * database, a log line, or an API response other than the single enable/rotate
 * reply that mints it.
 */

/** scrypt parameters for the read-only git remote password. */
export const SCRYPT_PARAMS = { N: 2 ** 15, r: 8, p: 1, keylen: 64 } as const;

/**
 * 128 * N * r is exactly 32 MiB at these parameters, which is the OpenSSL
 * default limit, so the derivation fails without an explicit headroom bump.
 */
const SCRYPT_MAXMEM = 128 * SCRYPT_PARAMS.N * SCRYPT_PARAMS.r * 2;

const SALT_BYTES = 16;

/** Bitcoin base58: no 0, O, I or l, so a hand-copied password is unambiguous. */
const BASE58_ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

export const GIT_PASSWORD_LENGTH = 32;

/** 32 characters of base58 from crypto.randomBytes. Shown to the user once. */
export function generateGitPassword(): string {
  const alphabet = BASE58_ALPHABET;
  // 256 is not a multiple of 58, so the naive modulo favours the first
  // 6 characters. Reject the tail of the byte range instead of biasing.
  const limit = Math.floor(256 / alphabet.length) * alphabet.length;
  let password = "";
  while (password.length < GIT_PASSWORD_LENGTH) {
    const chunk = randomBytes(GIT_PASSWORD_LENGTH);
    for (const byte of chunk) {
      if (byte >= limit) {
        continue;
      }
      password += alphabet[byte % alphabet.length];
      if (password.length === GIT_PASSWORD_LENGTH) {
        break;
      }
    }
  }
  return password;
}

function derive(password: string, salt: Buffer): Buffer {
  return scryptSync(Buffer.from(password, "utf8"), salt, SCRYPT_PARAMS.keylen, {
    N: SCRYPT_PARAMS.N,
    r: SCRYPT_PARAMS.r,
    p: SCRYPT_PARAMS.p,
    maxmem: SCRYPT_MAXMEM,
  });
}

/**
 * Self describing so a future parameter bump can still verify old hashes:
 * `scrypt$N$r$p$saltBase64$hashBase64`.
 */
export function hashGitPassword(password: string): string {
  if (password === "") {
    throw new Error("Refusing to hash an empty git remote password");
  }
  const salt = randomBytes(SALT_BYTES);
  const hash = derive(password, salt);
  const { N, r, p } = SCRYPT_PARAMS;
  return [
    "scrypt",
    String(N),
    String(r),
    String(p),
    salt.toString("base64"),
    hash.toString("base64"),
  ].join("$");
}

interface ParsedHash {
  N: number;
  r: number;
  p: number;
  salt: Buffer;
  hash: Buffer;
}

function parseStored(stored: string): ParsedHash | null {
  const parts = stored.split("$");
  if (parts.length !== 6 || parts[0] !== "scrypt") {
    return null;
  }
  const [, rawN, rawR, rawP, rawSalt, rawHash] = parts as [
    string,
    string,
    string,
    string,
    string,
    string,
  ];
  const N = Number.parseInt(rawN, 10);
  const r = Number.parseInt(rawR, 10);
  const p = Number.parseInt(rawP, 10);
  if (!Number.isSafeInteger(N) || !Number.isSafeInteger(r) || !Number.isSafeInteger(p)) {
    return null;
  }
  // Refuse absurd work factors: a tampered row must not turn a login into a
  // multi gigabyte allocation.
  if (N < 2 || N > 2 ** 20 || r < 1 || r > 32 || p < 1 || p > 16) {
    return null;
  }
  const salt = Buffer.from(rawSalt, "base64");
  const hash = Buffer.from(rawHash, "base64");
  // Lengths are pinned deliberately. scrypt finishes with a single PBKDF2
  // pass, whose output is prefix extensible: a hash truncated to a shorter
  // length would otherwise still verify. Amber is the only writer of this
  // record, so there is nothing to gain from accepting other lengths.
  if (salt.length !== SALT_BYTES || hash.length !== SCRYPT_PARAMS.keylen) {
    return null;
  }
  return { N, r, p, salt, hash };
}

/** Constant time comparison via timingSafeEqual. */
export function verifyGitPassword(password: string, stored: string): boolean {
  const parsed = parseStored(stored);
  if (parsed === null) {
    return false;
  }
  let candidate: Buffer;
  try {
    candidate = scryptSync(Buffer.from(password, "utf8"), parsed.salt, parsed.hash.length, {
      N: parsed.N,
      r: parsed.r,
      p: parsed.p,
      maxmem: 128 * parsed.N * parsed.r * 2,
    });
  } catch {
    return false;
  }
  // timingSafeEqual throws on a length mismatch, which would leak the length
  // through the exception path; the derivation above already pins the lengths
  // equal, and this guard keeps that true if the format ever changes.
  if (candidate.length !== parsed.hash.length) {
    return false;
  }
  return timingSafeEqual(candidate, parsed.hash);
}

/**
 * Constant time comparison for the basic auth username. Not a secret, but the
 * check sits next to the password check and should not short circuit on the
 * first differing byte either.
 */
export function safeEqualString(a: string, b: string): boolean {
  const left = Buffer.from(a, "utf8");
  const right = Buffer.from(b, "utf8");
  if (left.length !== right.length) {
    return false;
  }
  return timingSafeEqual(left, right);
}
