import { rm } from "node:fs/promises";
import { resolve, sep } from "node:path";
import {
  bulkRepoRequestSchema,
  deleteRepoQuerySchema,
  idParamsSchema,
  paginationQuerySchema,
  repoListQuerySchema,
  updateRepoSchema,
  type BulkRepoResponse,
  type Page,
  type Repo,
  type SyncRun,
} from "@amber/shared";
import type { FastifyPluginAsync } from "fastify";
import type { Config } from "../config.ts";
import { invalid } from "../domain/errors.ts";
import {
  bulkRepoAction,
  deleteRepo,
  listRepos,
  listSyncRuns,
  requestSyncNow,
  requireRepo,
  updateRepo,
  type RepoFileRemover,
} from "../domain/repos.ts";
import { repoDirFor } from "../repoDir.ts";
import { parseBody, parseParams, parseQuery } from "./validate.ts";

/**
 * Deletes a repo's backup directory. Kept out of domain/repos.ts so that
 * module does no filesystem IO, and gated twice: the slug must match the
 * strict generated pattern, and the resolved path must still sit inside
 * BACKUPS_DIR. A recursive delete driven by a database column earns both
 * checks even though every slug in the table was generated by us.
 */
export function createBackupFileRemover(config: Config): RepoFileRemover {
  const root = resolve(config.backupsDir);
  return async (repo: Repo): Promise<void> => {
    const dir = repoDirFor(config, repo);
    if (dir !== root && !dir.startsWith(root + sep)) {
      throw invalid("Refusing to delete a path outside the backups directory.");
    }
    await rm(dir, { recursive: true, force: true });
  };
}

/** /api/repos listing, detail, patch, delete, sync now, runs, and bulk actions. */
export const repoRoutes: FastifyPluginAsync = async (app) => {
  const { db, config, events, scheduler } = app.amber;
  const removeFiles = createBackupFileRemover(config);

  app.get("/repos", (request): Page<Repo> =>
    listRepos(db, parseQuery(repoListQuerySchema, request)),
  );

  // Registered before /repos/:id so the static segment wins the match.
  app.post("/repos/bulk", async (request): Promise<BulkRepoResponse> => {
    const body = parseBody(bulkRepoRequestSchema, request);
    const result = await bulkRepoAction(db, body.ids, body.action, {
      withFiles: body.files,
      removeFiles,
    });

    if (body.action === "sync" && scheduler !== undefined) {
      for (const id of result.ids) {
        scheduler.enqueueNow(id);
      }
    }
    for (const id of result.ids) {
      events.publish(body.action === "delete" ? "repo.deleted" : "repo.updated", {
        repoId: id,
      });
    }
    return result;
  });

  app.get("/repos/:id", (request): Repo => {
    const { id } = parseParams(idParamsSchema, request);
    return requireRepo(db, id);
  });

  app.patch("/repos/:id", (request): Repo => {
    const { id } = parseParams(idParamsSchema, request);
    const repo = updateRepo(db, id, parseBody(updateRepoSchema, request));
    events.publish("repo.updated", { repoId: repo.id });
    return repo;
  });

  app.delete("/repos/:id", async (request, reply): Promise<null> => {
    const { id } = parseParams(idParamsSchema, request);
    const { files } = parseQuery(deleteRepoQuerySchema, request);
    await deleteRepo(db, id, { withFiles: files, removeFiles });
    events.publish("repo.deleted", { repoId: id });
    void reply.code(204);
    return null;
  });

  /**
   * Persists next_sync_at first, then nudges the scheduler. The persisted row
   * is what makes this work with no scheduler attached yet: the request is
   * simply picked up on the next wake rather than lost.
   */
  app.post("/repos/:id/sync", (request): Repo => {
    const { id } = parseParams(idParamsSchema, request);
    const repo = requestSyncNow(db, id);
    scheduler?.enqueueNow(id);
    events.publish("repo.updated", { repoId: id });
    return repo;
  });

  app.get("/repos/:id/runs", (request): Page<SyncRun> => {
    const { id } = parseParams(idParamsSchema, request);
    return listSyncRuns(db, id, parseQuery(paginationQuerySchema, request));
  });
};
