import { randomBytes } from "node:crypto";
import type {
  BulkRepoAction,
  Page,
  PaginationQuery,
  Repo,
  RepoListQuery,
  RepoOrigin,
  RepoSortField,
  RepoState,
  SyncErrorKind,
  SyncOutcome,
  SyncRun,
  UpdateRepo,
} from "@amber/shared";
import type { Db } from "../db/db.ts";
import { conflict, invalid, isUniqueViolation, notFound } from "./errors.ts";
import { requireForge } from "./forges.ts";
import { resolveSettingsForRepos } from "./settings.ts";

/**
 * `forge_id` is IMMUTABLE. A repo cannot be re-pointed at another forge, which
 * would let it inherit that forge's (or its override account's) credentials
 * for a host it was never registered against. `path` may be edited, because a
 * rename stays on the same host.
 */

interface RepoRow {
  id: number;
  forge_id: number;
  path: string;
  display_name: string;
  slug: string;
  short_id: string;
  account_override_id: number | null;
  force_anonymous: number;
  managed_by_account_sync_id: number | null;
  state: string;
  next_sync_at: number | null;
  consecutive_failures: number;
  last_sync_at: number | null;
  last_success_at: number | null;
  last_error: string | null;
  disk_usage_bytes: number | null;
  default_branch: string | null;
  last_fetch_head: string | null;
  origin: string;
  created_at: number;
  updated_at: number;
}

const REPO_COLUMNS = `repos.id, repos.forge_id, repos.path, repos.display_name, repos.slug,
  repos.short_id, repos.account_override_id, repos.force_anonymous,
  repos.managed_by_account_sync_id, repos.state, repos.next_sync_at, repos.consecutive_failures,
  repos.last_sync_at, repos.last_success_at, repos.last_error, repos.disk_usage_bytes,
  repos.default_branch, repos.last_fetch_head, repos.origin, repos.created_at,
  repos.updated_at`;

function toRepo(row: RepoRow): Repo {
  return {
    id: row.id,
    forgeId: row.forge_id,
    path: row.path,
    displayName: row.display_name,
    slug: row.slug,
    shortId: row.short_id,
    accountOverrideId: row.account_override_id,
    forceAnonymous: row.force_anonymous === 1,
    managedByAccountSyncId: row.managed_by_account_sync_id,
    state: row.state as RepoState,
    nextSyncAt: row.next_sync_at,
    consecutiveFailures: row.consecutive_failures,
    lastSyncAt: row.last_sync_at,
    lastSuccessAt: row.last_success_at,
    lastError: row.last_error,
    diskUsageBytes: row.disk_usage_bytes,
    defaultBranch: row.default_branch,
    lastFetchHead: row.last_fetch_head,
    origin: row.origin as RepoOrigin,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

// ---------------------------------------------------------------------------
// Identity: short id, slug, path
// ---------------------------------------------------------------------------

const BASE36 = "0123456789abcdefghijklmnopqrstuvwxyz";
export const SHORT_ID_LENGTH = 8;
/** 256 is not a multiple of 36; bytes at or above this bias the low digits. */
const REJECT_AT = 256 - (256 % BASE36.length);

/** 8 characters of base36 from crypto.randomBytes. Unique per repo. */
export function generateShortId(): string {
  let out = "";
  while (out.length < SHORT_ID_LENGTH) {
    for (const byte of randomBytes(SHORT_ID_LENGTH * 2)) {
      if (byte >= REJECT_AT) {
        continue;
      }
      out += BASE36[byte % BASE36.length];
      if (out.length === SHORT_ID_LENGTH) {
        break;
      }
    }
  }
  return out;
}

/** Keep directory names readable without letting them grow unbounded. */
const MAX_SLUG_BODY = 64;

/**
 * Disk directory name: sanitized path + "-" + short_id. The short id makes
 * collisions impossible regardless of how two paths sanitize, so the
 * sanitizer is free to be aggressive.
 */
export function buildSlug(path: string, shortId: string): string {
  const body = path
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/-{2,}/g, "-")
    .replace(/^[-._]+/, "")
    .replace(/[-._]+$/, "")
    .slice(0, MAX_SLUG_BODY)
    .replace(/[-._]+$/, "");
  return `${body === "" ? "repo" : body}-${shortId}`;
}

/**
 * A slug becomes a directory name under BACKUPS_DIR and can drive a recursive
 * delete, so it is validated rather than trusted even though every slug in the
 * database was generated by buildSlug.
 */
const SAFE_SLUG_RE = /^[a-z0-9][a-z0-9._-]*$/;

export function isSafeSlug(slug: string): boolean {
  return (
    SAFE_SLUG_RE.test(slug) &&
    slug.length <= MAX_SLUG_BODY + SHORT_ID_LENGTH + 1 &&
    !slug.includes("..")
  );
}

export function assertSafeSlug(slug: string): string {
  if (!isSafeSlug(slug)) {
    throw invalid("Refusing to act on a repository with an unsafe directory name.");
  }
  return slug;
}

/** No leading or trailing slash, no trailing `.git`, no empty segments. */
export function normalizeRepoPath(path: string): string {
  const withoutDotGit = path.trim().replace(/\/+$/, "");
  const stripped =
    withoutDotGit.length >= 4 && withoutDotGit.slice(-4).toLowerCase() === ".git"
      ? withoutDotGit.slice(0, -4)
      : withoutDotGit;
  const segments = stripped.split("/").filter((segment) => segment !== "");
  if (segments.some((segment) => segment === "." || segment === "..")) {
    throw invalid("A repository path cannot contain relative segments.");
  }
  return segments.join("/");
}

export function displayNameFor(path: string): string {
  return path.slice(path.lastIndexOf("/") + 1);
}

// ---------------------------------------------------------------------------
// Reads
// ---------------------------------------------------------------------------

export function getRepo(db: Db, id: number): Repo | undefined {
  const row = db.get<RepoRow>(`SELECT ${REPO_COLUMNS} FROM repos WHERE repos.id = ?`, id);
  return row === undefined ? undefined : toRepo(row);
}

export function requireRepo(db: Db, id: number): Repo {
  const repo = getRepo(db, id);
  if (repo === undefined) {
    throw notFound("Repository", id);
  }
  return repo;
}

export function getRepoBySlug(db: Db, slug: string): Repo | undefined {
  // The git remote accepts an optional trailing `.git` on the clone URL.
  const normalized = slug.endsWith(".git") ? slug.slice(0, -4) : slug;
  const row = db.get<RepoRow>(`SELECT ${REPO_COLUMNS} FROM repos WHERE repos.slug = ?`, normalized);
  return row === undefined ? undefined : toRepo(row);
}

export function findRepoByPath(db: Db, forgeId: number, path: string): Repo | undefined {
  const row = db.get<RepoRow>(
    `SELECT ${REPO_COLUMNS} FROM repos WHERE repos.forge_id = ? AND repos.path = ?`,
    forgeId,
    path,
  );
  return row === undefined ? undefined : toRepo(row);
}

/**
 * Sort columns are looked up in this literal map rather than validated and
 * interpolated, so no user string can ever reach the SQL text. `dir` is mapped
 * the same way.
 */
const SORT_SQL: Readonly<Record<RepoSortField, string>> = {
  display_name: "repos.display_name COLLATE NOCASE",
  path: "repos.path COLLATE NOCASE",
  last_sync_at: "repos.last_sync_at",
  last_success_at: "repos.last_success_at",
  disk_usage_bytes: "repos.disk_usage_bytes",
  next_sync_at: "repos.next_sync_at",
  created_at: "repos.created_at",
};

const DIR_SQL: Readonly<Record<"asc" | "desc", string>> = { asc: "ASC", desc: "DESC" };

/** The outcome of the most recent run, used by the `outcome` filter. */
const LAST_OUTCOME_SQL = `(
  SELECT sr.outcome FROM sync_runs sr
  WHERE sr.repo_id = repos.id
  ORDER BY sr.started_at DESC, sr.id DESC
  LIMIT 1
)`;

/** The error classification of that same run, null on a successful one. */
const LAST_ERROR_KIND_SQL = `(
  SELECT sr.error_kind FROM sync_runs sr
  WHERE sr.repo_id = repos.id
  ORDER BY sr.started_at DESC, sr.id DESC
  LIMIT 1
)`;

/** Escape the LIKE wildcards so a search for "100%" is not a match-anything. */
function likePattern(term: string): string {
  return `%${term.replace(/[\\%_]/g, (char) => `\\${char}`)}%`;
}

export function listRepos(db: Db, query: RepoListQuery): Page<Repo> {
  const where: string[] = [];
  const params: (string | number)[] = [];

  if (query.q !== undefined && query.q.trim() !== "") {
    const pattern = likePattern(query.q.trim());
    where.push(`(repos.path LIKE ? ESCAPE '\\' OR repos.display_name LIKE ? ESCAPE '\\')`);
    params.push(pattern, pattern);
  }
  if (query.forgeId !== undefined) {
    where.push("repos.forge_id = ?");
    params.push(query.forgeId);
  }
  if (query.state !== undefined) {
    where.push("repos.state = ?");
    params.push(query.state);
  }
  if (query.outcome !== undefined) {
    where.push(`${LAST_OUTCOME_SQL} = ?`);
    params.push(query.outcome);
  }

  const whereSql = where.length === 0 ? "" : `WHERE ${where.join(" AND ")}`;

  const totalRow = db.get<{ count: number }>(
    `SELECT COUNT(*) AS count FROM repos ${whereSql}`,
    ...params,
  );
  const total = totalRow?.count ?? 0;

  const orderBy = SORT_SQL[query.sort];
  const direction = DIR_SQL[query.dir];
  const offset = (query.page - 1) * query.perPage;

  const rows = db.all<RepoRow & { last_outcome: string | null; last_error_kind: string | null }>(
    `SELECT ${REPO_COLUMNS},
            ${LAST_OUTCOME_SQL} AS last_outcome,
            ${LAST_ERROR_KIND_SQL} AS last_error_kind
       FROM repos ${whereSql}
      ORDER BY ${orderBy} ${direction}, repos.id ${direction}
      LIMIT ? OFFSET ?`,
    ...params,
    query.perPage,
    offset,
  );

  // One batch resolve for the whole page. The listing renders a mode column and
  // a sync-enabled state per row, neither of which is a column on `repos`;
  // resolving them per row would be several queries each.
  const settings = resolveSettingsForRepos(
    db,
    rows.map((row) => row.id),
  );

  const listed = rows.map((row): Repo => {
    const resolved = settings.get(row.id);
    return {
      ...toRepo(row),
      cloneMode: resolved?.clone_mode,
      syncEnabled: resolved?.sync_enabled,
      lastOutcome: row.last_outcome === null ? undefined : (row.last_outcome as SyncOutcome),
      lastErrorKind:
        row.last_error_kind === null ? undefined : (row.last_error_kind as SyncErrorKind),
    };
  });

  return { rows: listed, total, page: query.page, perPage: query.perPage };
}

export function countRepos(db: Db): number {
  return db.get<{ count: number }>("SELECT COUNT(*) AS count FROM repos")?.count ?? 0;
}

/** COALESCE keeps an empty table from reporting null bytes used. */
export function totalDiskUsageBytes(db: Db): number {
  const row = db.get<{ total: number }>(
    "SELECT COALESCE(SUM(disk_usage_bytes), 0) AS total FROM repos",
  );
  return row?.total ?? 0;
}

// ---------------------------------------------------------------------------
// Writes
// ---------------------------------------------------------------------------

export interface CreateRepoInput {
  forgeId: number;
  path: string;
  accountOverrideId?: number | null;
  forceAnonymous?: boolean;
  managedByAccountSyncId?: number | null;
  /** New repos sync immediately by default; the importer staggers a bulk run. */
  nextSyncAt?: number | null;
  state?: RepoState;
}

/** Retries only guard against an astronomically unlikely short id collision. */
const SHORT_ID_ATTEMPTS = 5;

export function createRepo(db: Db, input: CreateRepoInput): Repo {
  const path = normalizeRepoPath(input.path);
  if (path === "") {
    throw invalid("A repository needs a path.");
  }

  return db.tx(() => {
    requireForge(db, input.forgeId);
    const overrideId = input.accountOverrideId ?? null;
    if (overrideId !== null) {
      assertAccountBelongsToForge(db, overrideId, input.forgeId);
    }

    const now = Date.now();
    const nextSyncAt = input.nextSyncAt === undefined ? now : input.nextSyncAt;

    for (let attempt = 0; attempt < SHORT_ID_ATTEMPTS; attempt += 1) {
      const shortId = generateShortId();
      const slug = buildSlug(path, shortId);
      try {
        const id = db.run(
          `INSERT INTO repos
             (forge_id, path, display_name, slug, short_id, account_override_id,
              force_anonymous, managed_by_account_sync_id, state, next_sync_at,
              consecutive_failures, created_at, updated_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?, ?)`,
          input.forgeId,
          path,
          displayNameFor(path),
          slug,
          shortId,
          overrideId,
          input.forceAnonymous === true ? 1 : 0,
          input.managedByAccountSyncId ?? null,
          input.state ?? "active",
          nextSyncAt,
          now,
          now,
        ).lastInsertRowid;
        return requireRepo(db, id);
      } catch (error) {
        if (!isUniqueViolation(error)) {
          throw error;
        }
        // A duplicate forge+path is the caller's problem; a duplicate short id
        // is ours, and retrying with a fresh one resolves it.
        if (findRepoByPath(db, input.forgeId, path) !== undefined) {
          throw conflict(`"${path}" is already backed up from this forge.`, {
            forgeId: input.forgeId,
            path,
          });
        }
      }
    }
    throw conflict("Could not allocate a unique repository id. Please try again.");
  });
}

/** An override account must live on the repo's own forge. */
function assertAccountBelongsToForge(db: Db, accountId: number, forgeId: number): void {
  const row = db.get<{ forge_id: number }>("SELECT forge_id FROM accounts WHERE id = ?", accountId);
  if (row === undefined) {
    throw notFound("Account", accountId);
  }
  if (row.forge_id !== forgeId) {
    throw invalid(
      "That account belongs to a different forge. Credentials are never presented to a host " +
        "they were not registered for.",
      { accountId, accountForgeId: row.forge_id, repoForgeId: forgeId },
    );
  }
}

/**
 * State, account override, force_anonymous, and path. The forge is never part
 * of the update, and the slug deliberately stays fixed across a path edit so
 * the on-disk backup directory does not have to move.
 */
export function updateRepo(db: Db, id: number, patch: UpdateRepo): Repo {
  return db.tx(() => {
    const existing = requireRepo(db, id);
    const sets: string[] = [];
    const params: (string | number | null)[] = [];

    if (patch.state !== undefined && patch.state !== existing.state) {
      sets.push("state = ?");
      params.push(patch.state);
      if (patch.state === "active" && existing.nextSyncAt === null) {
        sets.push("next_sync_at = ?");
        params.push(Date.now());
      }
    }

    if (patch.accountOverrideId !== undefined) {
      if (patch.accountOverrideId !== null) {
        assertAccountBelongsToForge(db, patch.accountOverrideId, existing.forgeId);
      }
      sets.push("account_override_id = ?");
      params.push(patch.accountOverrideId);
    }

    if (patch.forceAnonymous !== undefined) {
      sets.push("force_anonymous = ?");
      params.push(patch.forceAnonymous ? 1 : 0);
    }

    if (patch.path !== undefined) {
      const path = normalizeRepoPath(patch.path);
      if (path === "") {
        throw invalid("A repository needs a path.");
      }
      if (path !== existing.path) {
        const clash = findRepoByPath(db, existing.forgeId, path);
        if (clash !== undefined) {
          throw conflict(`"${path}" is already backed up from this forge.`);
        }
        sets.push("path = ?", "display_name = ?");
        params.push(path, displayNameFor(path));
      }
    }

    if (sets.length === 0) {
      return existing;
    }

    sets.push("updated_at = ?");
    params.push(Date.now());
    params.push(id);
    db.run(`UPDATE repos SET ${sets.join(", ")} WHERE id = ?`, ...params);
    return requireRepo(db, id);
  });
}

/** Persisted request for an immediate sync. The scheduler picks this up. */
export function requestSyncNow(db: Db, id: number, at: number = Date.now()): Repo {
  return db.tx(() => {
    requireRepo(db, id);
    db.run("UPDATE repos SET next_sync_at = ?, updated_at = ? WHERE id = ?", at, at, id);
    return requireRepo(db, id);
  });
}

/** Removes the backup directory. Injected so this module does no filesystem IO. */
export type RepoFileRemover = (repo: Repo) => Promise<void>;

export interface DeleteRepoOptions {
  withFiles?: boolean;
  removeFiles?: RepoFileRemover;
}

/**
 * The database row goes first, then the files. A crash between the two leaves
 * an orphan directory, which is recoverable; the other order would leave a row
 * pointing at a backup that no longer exists.
 */
export async function deleteRepo(
  db: Db,
  id: number,
  options: DeleteRepoOptions = {},
): Promise<void> {
  const repo = requireRepo(db, id);
  if (options.withFiles === true && options.removeFiles === undefined) {
    throw invalid("Deleting the backup files needs a file remover.");
  }
  assertSafeSlug(repo.slug);

  db.run("DELETE FROM repos WHERE id = ?", id);

  if (options.withFiles === true && options.removeFiles !== undefined) {
    await options.removeFiles(repo);
  }
}

export interface BulkRepoResult {
  action: BulkRepoAction;
  requested: number;
  affected: number;
  /** The ids that were actually acted on; missing ids are skipped silently. */
  ids: number[];
  /** Ids that were requested but no longer exist. */
  missing: number[];
}

/**
 * Bulk pause, resume, sync, or delete. Missing ids are reported rather than
 * failing the whole batch, because a stale multi-select in the UI is normal.
 */
export async function bulkRepoAction(
  db: Db,
  ids: readonly number[],
  action: BulkRepoAction,
  options: DeleteRepoOptions = {},
): Promise<BulkRepoResult> {
  const acted: number[] = [];
  const missing: number[] = [];
  const now = Date.now();

  for (const id of ids) {
    const repo = getRepo(db, id);
    if (repo === undefined) {
      missing.push(id);
      continue;
    }
    switch (action) {
      case "pause":
        db.run("UPDATE repos SET state = 'paused', updated_at = ? WHERE id = ?", now, id);
        break;
      case "resume":
        db.run(
          `UPDATE repos SET state = 'active',
             next_sync_at = COALESCE(next_sync_at, ?), updated_at = ?
           WHERE id = ?`,
          now,
          now,
          id,
        );
        break;
      case "sync":
        db.run("UPDATE repos SET next_sync_at = ?, updated_at = ? WHERE id = ?", now, now, id);
        break;
      case "delete":
        await deleteRepo(db, id, options);
        break;
    }
    acted.push(id);
  }

  return { action, requested: ids.length, affected: acted.length, ids: acted, missing };
}

// ---------------------------------------------------------------------------
// Sync runs
// ---------------------------------------------------------------------------

interface SyncRunRow {
  id: number;
  repo_id: number;
  started_at: number;
  finished_at: number | null;
  outcome: string;
  error: string | null;
  error_kind: string | null;
  bytes_fetched: number | null;
  duration_ms: number | null;
  refs_changed: number | null;
  paranoid_archived: number | null;
}

function toSyncRun(row: SyncRunRow): SyncRun {
  return {
    id: row.id,
    repoId: row.repo_id,
    startedAt: row.started_at,
    finishedAt: row.finished_at,
    outcome: row.outcome as SyncRun["outcome"],
    error: row.error,
    errorKind: row.error_kind as SyncRun["errorKind"],
    bytesFetched: row.bytes_fetched,
    durationMs: row.duration_ms,
    refsChanged: row.refs_changed,
    paranoidArchived: row.paranoid_archived,
  };
}

export function listSyncRuns(db: Db, repoId: number, query: PaginationQuery): Page<SyncRun> {
  requireRepo(db, repoId);
  const total =
    db.get<{ count: number }>("SELECT COUNT(*) AS count FROM sync_runs WHERE repo_id = ?", repoId)
      ?.count ?? 0;
  const rows = db.all<SyncRunRow>(
    `SELECT id, repo_id, started_at, finished_at, outcome, error, error_kind,
            bytes_fetched, duration_ms, refs_changed, paranoid_archived
     FROM sync_runs WHERE repo_id = ?
     ORDER BY started_at DESC, id DESC
     LIMIT ? OFFSET ?`,
    repoId,
    query.perPage,
    (query.page - 1) * query.perPage,
  );
  return { rows: rows.map(toSyncRun), total, page: query.page, perPage: query.perPage };
}
