import { spawn, type ChildProcess } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { SyncErrorKind } from "@amber/shared";
import type { Logger } from "pino";

/**
 * The only place in the codebase that runs git. spawn with argument arrays,
 * never a shell. Credentials never enter argv or stored remote URLs: auth goes
 * through a one-shot GIT_ASKPASS script reading AMBER_GIT_USER/AMBER_GIT_PASS,
 * which refuses to answer when git prompts for a host other than the one the
 * credential belongs to.
 */
export interface GitRunOptions {
  cwd?: string;
  /** Injected via askpass env, never via argv or the remote URL. */
  credentials?: { username: string; password: string };
  /**
   * host[:port] the credentials belong to, as produced by `new URL(remote).host`.
   * Derived from the first http(s) URL in argv when omitted; required (directly
   * or by derivation) whenever credentials are passed.
   */
  expectedHost?: string;
  /** Hard kill timer. Defaults to 1h for fetch/clone, 10 min for plumbing. */
  timeoutMs?: number;
  /** Extra -c overrides on top of the pinned hardening set. */
  config?: Record<string, string>;
  env?: Record<string, string>;
  maxBufferBytes?: number;
  /** Fed to the child's stdin, which is closed immediately when absent. */
  stdin?: string;
  /** Adds the working-tree hardening (hooks path, fsmonitor, lfs filters). */
  workingTree?: boolean;
  /** Test-only: widens GIT_ALLOW_PROTOCOL to include file:// origins. */
  allowFileProtocol?: boolean;
  /** Resolve with a non-zero exit instead of throwing GitError. */
  allowFailure?: boolean;
  /** Directory that holds the scrubbed HOME, the hooks dir and the askpass helper. */
  stateDir?: string;
  logger?: Logger;
  /** Defaults to "git". Only ever a binary name, never repo-controlled. */
  binary?: string;
}

export interface GitResult {
  stdout: string;
  stderr: string;
  code: number;
  durationMs: number;
  /** True when either stream hit maxBufferBytes and was cut short. */
  truncated: boolean;
  timedOut: boolean;
  args: readonly string[];
}

export const DEFAULT_FETCH_TIMEOUT_MS = 60 * 60 * 1000;
export const DEFAULT_PLUMBING_TIMEOUT_MS = 10 * 60 * 1000;
export const DEFAULT_MAX_BUFFER_BYTES = 4 * 1024 * 1024;
/** Grace period between SIGTERM and SIGKILL during shutdown. */
export const SHUTDOWN_GRACE_MS = 5000;

/** Subcommands that talk to a remote and therefore get the long timeout. */
const NETWORK_COMMANDS = new Set(["fetch", "clone", "ls-remote", "lfs"]);

export class GitError extends Error {
  override readonly name = "GitError";
  readonly kind: SyncErrorKind;
  readonly code: number;
  readonly stdout: string;
  readonly stderr: string;
  readonly args: readonly string[];
  readonly durationMs: number;
  readonly timedOut: boolean;

  constructor(message: string, result: GitResult, kind: SyncErrorKind) {
    super(message);
    this.kind = kind;
    this.code = result.code;
    this.stdout = result.stdout;
    this.stderr = result.stderr;
    this.args = result.args;
    this.durationMs = result.durationMs;
    this.timedOut = result.timedOut;
  }
}

// ---------------------------------------------------------------------------
// Runtime: scrubbed HOME, empty hooks dir, pinned empty config, askpass helper
// ---------------------------------------------------------------------------

export interface GitRuntime {
  readonly root: string;
  readonly homeDir: string;
  readonly hooksDir: string;
  readonly configPath: string;
  readonly askpassPath: string;
  /** The literal GIT_ASKPASS value handed to git. */
  readonly askpassCommand: string;
}

/**
 * The askpass helper. It answers only when git's prompt names the exact host
 * the credential belongs to, so a forge that redirects to a look-alike host
 * cannot phish a stored token. Anything unexpected produces empty output,
 * which git treats as "no credential available".
 */
const ASKPASS_SOURCE = `#!/usr/bin/env node
// Generated by amber (server/src/sync/gitCli.ts). Do not edit.
// git execs this file directly (no shell), passing the prompt as argv[2]. The
// shebang resolves through /usr/bin/env on Linux and through Git for Windows'
// shebang handling on Windows, so both platforms run the same helper.
// Answers git credential prompts from AMBER_GIT_USER / AMBER_GIT_PASS, but
// only when the prompt names AMBER_GIT_HOST exactly. Any other host, or an
// unparseable prompt, yields empty output so git gives up instead of leaking
// the credential to whatever host it was redirected to.
"use strict";
const prompt = process.argv[2] || "";
const expected = (process.env.AMBER_GIT_HOST || "").trim().toLowerCase();
if (expected === "") {
  process.exit(0);
}
// git asks: Username for 'https://host': / Password for 'https://user@host':
const match = /'([A-Za-z][A-Za-z0-9+.-]*:\\/\\/[^']*)'/.exec(prompt);
if (match === null) {
  process.exit(0);
}
let host = "";
try {
  host = new URL(match[1]).host.toLowerCase();
} catch {
  process.exit(0);
}
if (host === "" || host !== expected) {
  process.exit(0);
}
if (/^password/i.test(prompt.trim())) {
  process.stdout.write((process.env.AMBER_GIT_PASS || "") + "\\n");
} else if (/^username/i.test(prompt.trim())) {
  process.stdout.write((process.env.AMBER_GIT_USER || "") + "\\n");
}
process.exit(0);
`;

let cachedRuntime: GitRuntime | undefined;

/** A newline in the path would truncate what git execs. Nothing else can hurt. */
const UNSAFE_IN_ASKPASS_COMMAND = /[\r\n]/;

function toPosixPath(value: string): string {
  return value.replace(/\\/g, "/");
}

/**
 * Create (idempotently) the amber-owned git runtime directories and the askpass
 * helper. Lazily invoked so nothing touches the filesystem at import time.
 */
export function ensureGitRuntime(stateDir?: string): GitRuntime {
  const root = join(stateDir ?? join(tmpdir(), "amber-git-runtime"), "git");
  if (cachedRuntime !== undefined && cachedRuntime.root === root) {
    return cachedRuntime;
  }

  const homeDir = join(root, "home");
  const hooksDir = join(root, "hooks");
  const configPath = join(homeDir, "gitconfig");
  const askpassPath = join(root, "askpass.mjs");

  mkdirSync(homeDir, { recursive: true });
  mkdirSync(hooksDir, { recursive: true });
  mkdirSync(join(homeDir, "config"), { recursive: true });
  writeFileSync(configPath, "# amber pins git to an empty global config\n", "utf8");
  // Executable: git spawns GIT_ASKPASS directly, it does not go through a shell.
  writeFileSync(askpassPath, ASKPASS_SOURCE, { encoding: "utf8", mode: 0o755 });

  if (UNSAFE_IN_ASKPASS_COMMAND.test(askpassPath)) {
    throw new Error(`Refusing to use an askpass path containing a newline: ${askpassPath}`);
  }
  const askpassCommand = askpassPath;

  cachedRuntime = { root, homeDir, hooksDir, configPath, askpassPath, askpassCommand };
  return cachedRuntime;
}

/** Test hook: forget the cached runtime so the next call rebuilds it. */
export function resetGitRuntime(): void {
  cachedRuntime = undefined;
}

// ---------------------------------------------------------------------------
// Environment and argument hardening
// ---------------------------------------------------------------------------

/**
 * The only parent environment variables a git child inherits. PATH matters:
 * git resolves both its own helpers and the `sh` it uses for GIT_ASKPASS
 * through it. Everything else (GIT_*, SSH_*, proxies, locales) is dropped.
 */
const INHERITED_ENV_KEYS = [
  "PATH",
  "PATHEXT",
  "SYSTEMROOT",
  "WINDIR",
  "SYSTEMDRIVE",
  "COMSPEC",
  "TEMP",
  "TMP",
  "TMPDIR",
  "TZ",
];

function inheritedEnv(): Record<string, string> {
  const wanted = new Set(INHERITED_ENV_KEYS);
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(process.env)) {
    if (value !== undefined && wanted.has(key.toUpperCase())) {
      out[key] = value;
    }
  }
  return out;
}

function buildEnv(
  runtime: GitRuntime,
  options: GitRunOptions,
  args: readonly string[],
): Record<string, string> {
  const protocols = options.allowFileProtocol === true ? "https:http:file" : "https:http";
  const env: Record<string, string> = {
    ...inheritedEnv(),
    // No system config, no global config, no user home to discover one in.
    GIT_CONFIG_NOSYSTEM: "1",
    GIT_CONFIG_GLOBAL: runtime.configPath,
    GIT_ATTR_NOSYSTEM: "1",
    HOME: runtime.homeDir,
    USERPROFILE: runtime.homeDir,
    XDG_CONFIG_HOME: join(runtime.homeDir, "config"),
    GIT_ALLOW_PROTOCOL: protocols,
    GIT_LFS_SKIP_SMUDGE: "1",
    GIT_TERMINAL_PROMPT: "0",
    GIT_ASKPASS: runtime.askpassCommand,
    // Deterministic, parseable stderr for error classification.
    LC_ALL: "C",
    LANG: "C",
    ...options.env,
  };

  if (options.credentials !== undefined) {
    const host = options.expectedHost ?? deriveExpectedHost(args);
    if (host === undefined || host === "") {
      throw new Error(
        "runGit was given credentials without an expected host; refusing to run so a " +
          "credential cannot be offered to an unverified origin",
      );
    }
    env.AMBER_GIT_HOST = host;
    env.AMBER_GIT_USER = options.credentials.username;
    env.AMBER_GIT_PASS = options.credentials.password;
  }

  return env;
}

/** Last resort: take the host from the single http(s) URL in argv. */
function deriveExpectedHost(args: readonly string[]): string | undefined {
  const hosts = new Set<string>();
  for (const arg of args) {
    if (/^https?:\/\//i.test(arg)) {
      try {
        hosts.add(new URL(arg).host.toLowerCase());
      } catch {
        // Not a URL after all; ignore.
      }
    }
  }
  return hosts.size === 1 ? [...hosts][0] : undefined;
}

/** host[:port] for an http(s) remote, as the askpass helper will see it. */
export function expectedHostForRemote(remoteUrl: string): string {
  return new URL(remoteUrl).host.toLowerCase();
}

function configArgs(runtime: GitRuntime, options: GitRunOptions): string[] {
  const config: Record<string, string> = {
    "protocol.version": "2",
    "transfer.credentialsInUrl": "die",
    "http.followRedirects": "initial",
    "submodule.recurse": "false",
    "fetch.recurseSubmodules": "no",
    // No credential helper can be reached anyway (empty global config), but
    // pinning it empty means a repo-local config cannot introduce one either.
    "credential.helper": "",
    "advice.detachedHead": "false",
    "init.defaultBranch": "main",
    // Hooks live in an amber-owned empty directory for every invocation, not
    // just working-tree ones: a restored backup must never be able to run code.
    "core.hooksPath": toPosixPath(runtime.hooksDir),
  };
  if (options.workingTree === true) {
    config["core.fsmonitor"] = "false";
    config["filter.lfs.required"] = "false";
    config["filter.lfs.smudge"] = "";
    config["filter.lfs.process"] = "";
  }
  Object.assign(config, options.config);

  const args: string[] = [];
  for (const [key, value] of Object.entries(config)) {
    args.push("-c", `${key}=${value}`);
  }
  return args;
}

/** Userinfo in a URL, the one shape that would put a credential in argv. */
const URL_WITH_USERINFO = /[A-Za-z][A-Za-z0-9+.-]*:\/\/[^/\s]*@/;

function assertSafeArgs(args: readonly string[], options: GitRunOptions): void {
  for (const arg of args) {
    if (URL_WITH_USERINFO.test(arg)) {
      throw new Error(
        "Refusing to run git with a URL that carries userinfo; credentials go through askpass",
      );
    }
  }
  const password = options.credentials?.password;
  if (password !== undefined && password !== "") {
    for (const arg of args) {
      if (arg.includes(password)) {
        throw new Error("Refusing to run git with a credential present in argv");
      }
    }
  }
}

function subcommandOf(args: readonly string[]): string {
  for (const arg of args) {
    if (!arg.startsWith("-")) {
      return arg;
    }
  }
  return "";
}

function defaultTimeoutMs(args: readonly string[]): number {
  return NETWORK_COMMANDS.has(subcommandOf(args))
    ? DEFAULT_FETCH_TIMEOUT_MS
    : DEFAULT_PLUMBING_TIMEOUT_MS;
}

/** Strip any userinfo before text derived from git output reaches a log or the DB. */
export function scrubCredentials(text: string): string {
  return text.replace(/([A-Za-z][A-Za-z0-9+.-]*:\/\/)[^/\s]*@/g, "$1");
}

// ---------------------------------------------------------------------------
// Process tracking and execution
// ---------------------------------------------------------------------------

interface TrackedChild {
  child: ChildProcess;
  description: string;
}

const activeChildren = new Set<TrackedChild>();

export function activeGitProcessCount(): number {
  return activeChildren.size;
}

function killChild(child: ChildProcess, signal: NodeJS.Signals): void {
  if (child.pid === undefined || child.exitCode !== null || child.signalCode !== null) {
    return;
  }
  try {
    if (process.platform === "win32") {
      // git spawns transport helpers (git-remote-https and friends) that hold
      // the pipes open, so killing only the parent leaves the pipeline alive.
      const killer = spawn("taskkill", ["/PID", String(child.pid), "/T", "/F"], {
        windowsHide: true,
        stdio: "ignore",
      });
      killer.on("error", () => {
        child.kill(signal);
      });
    } else {
      // The child leads its own process group (detached), so this reaches the
      // transport helpers git spawned as well.
      process.kill(-child.pid, signal);
    }
  } catch {
    // Already gone.
  }
}

function boundedCollector(limit: number): {
  push: (chunk: Buffer) => void;
  text: () => string;
  truncated: () => boolean;
} {
  const chunks: Buffer[] = [];
  let size = 0;
  let cut = false;
  return {
    push(chunk: Buffer) {
      if (size >= limit) {
        cut = true;
        return;
      }
      const room = limit - size;
      if (chunk.length > room) {
        chunks.push(chunk.subarray(0, room));
        size = limit;
        cut = true;
        return;
      }
      chunks.push(chunk);
      size += chunk.length;
    },
    text() {
      return Buffer.concat(chunks).toString("utf8");
    },
    truncated() {
      return cut;
    },
  };
}

export async function runGit(
  args: readonly string[],
  options: GitRunOptions = {},
): Promise<GitResult> {
  const runtime = ensureGitRuntime(options.stateDir);
  assertSafeArgs(args, options);

  const finalArgs = [...configArgs(runtime, options), ...args];
  const env = buildEnv(runtime, options, args);
  const timeoutMs = options.timeoutMs ?? defaultTimeoutMs(args);
  const limit = options.maxBufferBytes ?? DEFAULT_MAX_BUFFER_BYTES;
  const binary = options.binary ?? "git";
  const log = options.logger;
  const startedAt = Date.now();

  const result = await new Promise<GitResult>((settle, fail) => {
    const child = spawn(binary, finalArgs, {
      cwd: options.cwd,
      env,
      shell: false,
      windowsHide: true,
      detached: process.platform !== "win32",
      stdio: ["pipe", "pipe", "pipe"],
    });

    const tracked: TrackedChild = { child, description: subcommandOf(args) };
    activeChildren.add(tracked);

    const stdout = boundedCollector(limit);
    const stderr = boundedCollector(limit);
    let timedOut = false;
    let done = false;

    const timer = setTimeout(() => {
      timedOut = true;
      killChild(child, "SIGKILL");
    }, timeoutMs);
    // A pending kill timer must never keep the process alive on its own.
    timer.unref?.();

    const finish = (code: number): void => {
      if (done) {
        return;
      }
      done = true;
      clearTimeout(timer);
      activeChildren.delete(tracked);
      settle({
        stdout: stdout.text(),
        stderr: stderr.text(),
        code,
        durationMs: Date.now() - startedAt,
        truncated: stdout.truncated() || stderr.truncated(),
        timedOut,
        // The exact argv that was spawned, so tests and the debug log see what
        // git really received rather than what the caller asked for.
        args: finalArgs,
      });
    };

    child.stdout?.on("data", (chunk: Buffer) => {
      stdout.push(chunk);
    });
    child.stderr?.on("data", (chunk: Buffer) => {
      stderr.push(chunk);
    });

    child.on("error", (error) => {
      if (done) {
        return;
      }
      done = true;
      clearTimeout(timer);
      activeChildren.delete(tracked);
      fail(error);
    });

    child.on("close", (code, signal) => {
      finish(code ?? (signal === null ? 1 : 128));
    });

    // A killed git can leave a transport helper holding the pipes, in which
    // case "close" never arrives. Once the process itself is gone, give the
    // streams a moment to drain and then settle regardless.
    child.on("exit", (code, signal) => {
      const drain = setTimeout(() => {
        finish(code ?? (signal === null ? 1 : 128));
      }, 500);
      drain.unref?.();
    });

    if (child.stdin !== null) {
      child.stdin.on("error", () => {
        // git closing stdin early (for example on a bad argument) is not fatal.
      });
      if (options.stdin !== undefined) {
        child.stdin.end(options.stdin);
      } else {
        child.stdin.end();
      }
    }
  });

  log?.debug(
    {
      git: result.args.map(scrubCredentials),
      cwd: options.cwd,
      code: result.code,
      durationMs: result.durationMs,
      timedOut: result.timedOut,
    },
    "git finished",
  );

  if (result.code !== 0 && options.allowFailure !== true) {
    const kind = classifyGitFailure(result.stderr, result.code, result.timedOut);
    const detail = scrubCredentials(result.stderr.trim() || result.stdout.trim());
    throw new GitError(
      `git ${subcommandOf(args)} failed (${String(result.code)}): ${detail.slice(0, 500)}`,
      result,
      kind,
    );
  }

  return result;
}

/**
 * Streaming variant for upload-pack, where stdin and stdout are piped. The
 * caller owns the returned child and must not let it outlive the request.
 */
export function spawnGit(args: readonly string[], options: GitRunOptions = {}): ChildProcess {
  const runtime = ensureGitRuntime(options.stateDir);
  assertSafeArgs(args, options);
  const child = spawn(options.binary ?? "git", [...configArgs(runtime, options), ...args], {
    cwd: options.cwd,
    env: buildEnv(runtime, options, args),
    shell: false,
    windowsHide: true,
    stdio: ["pipe", "pipe", "pipe"],
  });
  const tracked: TrackedChild = { child, description: subcommandOf(args) };
  activeChildren.add(tracked);
  const timer = setTimeout(
    () => {
      killChild(child, "SIGKILL");
    },
    options.timeoutMs ?? defaultTimeoutMs(args),
  );
  timer.unref?.();
  child.on("close", () => {
    clearTimeout(timer);
    activeChildren.delete(tracked);
  });
  return child;
}

/** Kill every tracked git child on shutdown. */
export async function shutdownGit(graceMs: number = SHUTDOWN_GRACE_MS): Promise<void> {
  if (activeChildren.size === 0) {
    return;
  }
  const waiting = [...activeChildren];
  for (const tracked of waiting) {
    killChild(tracked.child, "SIGTERM");
  }

  const exits = waiting.map(
    (tracked) =>
      new Promise<void>((done) => {
        if (tracked.child.exitCode !== null || tracked.child.signalCode !== null) {
          done();
          return;
        }
        tracked.child.once("exit", () => {
          done();
        });
      }),
  );

  const settled = await Promise.race([
    Promise.all(exits).then(() => true),
    new Promise<boolean>((done) => {
      const timer = setTimeout(() => {
        done(false);
      }, graceMs);
      timer.unref?.();
    }),
  ]);

  if (!settled) {
    for (const tracked of waiting) {
      killChild(tracked.child, "SIGKILL");
    }
    await Promise.all(exits);
  }
  for (const tracked of waiting) {
    activeChildren.delete(tracked);
  }
}

// ---------------------------------------------------------------------------
// Error classification
// ---------------------------------------------------------------------------

const RATE_LIMITED = /rate limit|too many requests|\b429\b|retry-after|slow down/i;
const AUTH = new RegExp(
  [
    "authentication failed",
    "could not read username",
    "could not read password",
    "invalid username or password",
    "terminal prompts disabled",
    "\\b401\\b",
    "\\b403\\b",
    "permission denied",
    "access denied",
    "support for password authentication was removed",
    "bad credentials",
    "requested url returned error: 40[13]",
  ].join("|"),
  "i",
);
const NOT_FOUND = new RegExp(
  [
    "repository not found",
    "\\b404\\b",
    "does not appear to be a git repository",
    "not found: did you run git update-server-info",
    "remote: repository .* not found",
    "no such file or directory",
    "does not exist",
  ].join("|"),
  "i",
);
const NETWORK = new RegExp(
  [
    "could not resolve host",
    "couldn't resolve host",
    "connection refused",
    "connection timed out",
    "connection reset",
    "network is unreachable",
    "no route to host",
    "failed to connect",
    "unable to access",
    "ssl",
    "tls",
    "gnutls",
    "recv failure",
    "send failure",
    "empty reply from server",
    "early eof",
    "rpc failed",
    "the remote end hung up",
    "unexpected disconnect",
    "operation timed out",
    "proxy",
  ].join("|"),
  "i",
);
const DISK =
  /no space left on device|disk quota exceeded|cannot write|write error|read-only file system/i;
const TIMEOUT = /timed out|timeout/i;

/**
 * Map git stderr and exit codes onto the sync_runs.error_kind vocabulary.
 * Order matters: rate limiting looks like an auth failure, and "404" looks
 * like a network error once curl wraps it.
 */
export function classifyGitFailure(stderr: string, code: number, timedOut = false): SyncErrorKind {
  if (timedOut) {
    return "timeout";
  }
  const text = stderr;
  if (RATE_LIMITED.test(text)) {
    return "rate_limited";
  }
  if (AUTH.test(text)) {
    return "auth";
  }
  if (NOT_FOUND.test(text)) {
    return "not_found";
  }
  if (DISK.test(text)) {
    return "disk";
  }
  if (NETWORK.test(text)) {
    return "network";
  }
  if (TIMEOUT.test(text)) {
    return "timeout";
  }
  if (code !== 0) {
    return "git";
  }
  return "other";
}
