import { resolve } from "node:path";
import type { Repo } from "@amber/shared";
import type { Config } from "./config.ts";
import { assertSafeSlug } from "./domain/repos.ts";

/**
 * The single definition of "where a repo's backup lives on disk". Every caller
 * that reads a backup (git remote, exports) and the one that deletes it go
 * through here, so the serving and deleting paths cannot drift apart.
 *
 * The slug always comes from a repos row rather than from a request, but it is
 * still run through assertSafeSlug: a recursive delete and a spawned git
 * process both earn the check even though every slug in the table was
 * generated by us.
 */
export function repoDirFor(config: Pick<Config, "backupsDir">, repo: Pick<Repo, "slug">): string {
  return resolve(config.backupsDir, assertSafeSlug(repo.slug));
}
